development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

production:
  adapter: mysql2
  encoding: utf-8  
  reconnect: false
  database: oishinbo
  user: user_name
  password: password
  host: localhost
